### ISSUE TITLE
New release with `:where()`?

### ISSUE THREAD

**Issue by mikestopcontinues** [csstools/normalize.css#20]
Hi! I'd really like to reference the newest updates using `:where()`. Can you release it, even with a beta tag?

**Comment by jonathantneal** [comment]
Yea, here it comes. Just a moment.

**Comment by jonathantneal** [comment]
Done!

**Comment by bjankord** [comment]
@jonathantneal Curious, what's the idea behind using :where() in this project?

**Comment by therealpecus** [comment]
> @jonathantneal Curious, what's the idea behind using :where() in this project?

I would say to remove additional specificity. 

The side effect is that normalize is now looking at a very strict and recent browser matrix (see the compatibility chart). IMHO it kinda limits the benefits of including normalize in projects that try to support relatively older browsers, as differences are a lot more significant the more you go back in time. Personally I would like to see `postcss-preset-env`  take care of removing redundant normalization declarations (_and_ converting `:where` selectors to more compatible element selectors) rather than seeing normalize.css being stripped down and converted to recent syntax without a chance to make it more backwards compatible.
