### ISSUE TITLE
Remove Gray Highlight When Tapping Links in Mobile Safari

### ISSUE THREAD

**Issue by iMaximal** [csstools/normalize.css#6]
There is unexpected behavior in iOS devices.
When user tap, gray background is exist.

To fix, we should add to html/body:
```
/* Remove Gray Highlight When Tapping Links in Mobile Safari */
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
```

Proof (and bug in my project):
https://css-tricks.com/snippets/css/remove-gray-highlight-when-tapping-links-in-mobile-safari/

Thanks!

**Comment by jonathantneal** [comment]
This seems useful as an opinionated style, since it would neither fix a bug or resolve a cross browser incompatibility with the way tapped links are displayed. From the comments, it appears Android/iOS agree on the gray, while developers would generally prefer it were absent. Moving this to https://github.com/csstools/sanitize.css/pull/179
